authapp/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('read_profile/', authapp.read_profile, name='read_profile'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
    path('send/mail/confirm/', TemplateView.as_view(template_name='authapp/send_confirm.html'), name='send_confirm'),
]

mainapp/urls.py
import mainapp.views as mainapp
from django.urls import path

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('post/<slug:slug>/', mainapp.post, name='post'),
    path('help/', mainapp.help, name='help'),
    path('category/<slug:slug>/', mainapp.category_page, name='category_page'),
    path('changelike/<slug:slug>/', mainapp.change_like, name='change_like'),
    path('search/', mainapp.SearchResultsView.as_view(), name='search_results'),
    path('delete/comment/', mainapp.delete_comment, name='delete_comment'),
    path('to/banish/', mainapp.to_banish, name='to_banish'),
]

xabr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from xabr import settings

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('blog/', include('blogapp.urls', namespace='blogapp')),
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from datetime import timedelta
from django.core.mail import send_mail
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.utils.timezone import now
from xabr import settings


def get_activation_key_express():
    """функция для получения ключа активации пользователя"""

    return now() + timedelta(hours=48)


class XabrUser(AbstractUser):
    """модель пользователя"""

    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name='возраст', default=18, blank=True)
    aboutMe = models.TextField(verbose_name='о себе', max_length=512, blank=True)
    email = models.EmailField(verbose_name='email', unique=True, blank=False)
    activation_key = models.CharField(max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(default=(now() + timedelta(hours=48)))
    like_quantity = models.PositiveIntegerField('кол-во', default=0)
    is_active = models.BooleanField(verbose_name='активен/неактивен', default=True)
    is_staff = models.BooleanField(verbose_name='статус персонала', default=False)

    def is_activation_key_expired(self):
        """функция активации пользователя"""
        if now() <= self.activation_key_expires:
            return False
        else:
            return True

    def send_verify_mail(self):
        """функция подтверждения учетной записи"""

        verify_link = reverse(
            'auth:verify',
            kwargs={
                'email': self.email,
                'activation_key': self.activation_key
            },
        )
        title = f'Подтверждение учетной записи {self.username}'
        message = f'Для подтверждения учетной записи {self.username} на портале ' \
                  f'{settings.DOMAIN_NAME} перейдите по ссылке: \n{settings.DOMAIN_NAME}{verify_link}'

        return send_mail(title, message, settings.EMAIL_HOST_USER, [self.email], fail_silently=False)

authapp/forms.py
import hashlib
import random
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from django.forms import TextInput
from .models import XabrUser


class XabrUserLoginForm(AuthenticationForm):
    """форма аутентификации пользователя"""

    class Meta:
        model = XabrUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'form-control {field_name}'
            if field_name == 'password':
                field.widget.attrs['placeholder'] = f'Пароль'
            else:
                field.widget.attrs['placeholder'] = f'Имя пользователя'


class XabrUserRegisterForm(UserCreationForm):
    """форма регистрации пользователя"""

    class Meta:
        model = XabrUser
        fields = ('username', 'first_name', 'email', 'password1', 'password2', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def save(self, commit=True):
        user = super(XabrUserRegisterForm, self).save()

        user.is_active = False
        salt = hashlib.sha1(str(random.random()).encode('utf8')).hexdigest()[:6]
        user.activation_key = hashlib.sha1((user.email + salt).encode('utf8')).hexdigest()
        user.save()

        return user


class XabrUserEditForm(UserChangeForm):
    """форма редактирования данных пользователя"""

    class Meta:
        model = XabrUser
        fields = ('username', 'first_name', 'email', 'age', 'aboutMe', 'avatar', 'password')
        widgets = {
            'username': TextInput(attrs={'id': 'id_username', 'readonly': 'readonly'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from authapp.forms import XabrUserLoginForm
from django.contrib import auth
from django.urls import reverse
from authapp.forms import XabrUserRegisterForm, XabrUserEditForm
from authapp.models import XabrUser
from mainapp.models import Category, Post


def login(request):
    """контроллер для выводв страницы авторизации/регистрации пользователя"""

    title = 'вход'
    next = request.GET['next'] if 'next' in request.GET.keys() else ''
    login_form = XabrUserLoginForm(data=request.POST)

    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect(reverse('main:index'))

    content = {'title': title, 'login_form': login_form, 'next': next, }
    return render(request, 'authapp/login.html', content)


def logout(request):
    """контроллер выхода пользователя из личного кабинета"""

    auth.logout(request)
    return HttpResponseRedirect(reverse('main:index'))


def register(request):
    """контроллер для вывода формы регистрации (ввода данных) пользователя"""

    next = request.GET['next'] if 'next' in request.GET.keys() else ''

    if request.method == 'POST':
        register_form = XabrUserRegisterForm(request.POST, request.FILES)
        if register_form.is_valid():
            user = register_form.save()
            if user.send_verify_mail():
                print('сообщение подтверждения отправлено')
                return HttpResponseRedirect(reverse('auth:send_confirm'))
            else:
                print('ошибка отправки сообщения')
            return HttpResponseRedirect(reverse('mainapp:index'))
    else:
        register_form = XabrUserRegisterForm()
    content = {
        'title': 'регистрация пользователя',
        'register_form': register_form,
        'next': next,
    }
    return render(request, 'authapp/register.html', content)


@login_required
def read_profile(request):
    """контроллер для вывода профиля пользователя"""

    categories = Category.objects.all()
    posts = Post.objects.filter(user=request.user).order_by('-create_datetime')
    user = request.user

    content = {
        'title': 'Профиль пользователя',
        'user': user,
        'posts': posts,
        'categories': categories,
    }
    return render(request, 'authapp/read_profile.html', content)


@login_required
def edit(request):
    """функция для редактирования профиля пользователя"""

    title = 'редактирование'

    if request.method == 'POST':
        edit_form = XabrUserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:read_profile'))
    else:
        edit_form = XabrUserEditForm(instance=request.user)

    content = {
        'title': title,
        'edit_form': edit_form,
    }

    return render(request, 'authapp/edit.html', content)


def verify(request, email, activation_key):
    """контроллер для вывода подтверждения/не подтверждения регистрации"""

    try:
        user = XabrUser.objects.get(email=email)
        if user.activation_key == activation_key and not user.is_activation_key_expired():
            user.is_active = True
            user.save()
            auth.login(request, user,
                       backend='django.contrib.auth.backends.ModelBackend')
        else:
            print(f'error activation user: {user}')
        return render(request, 'authapp/verification.html')
    except Exception as e:
        print(f'error activation user : {e.args}')
        return HttpResponseRedirect(reverse('mainapp:index'))

authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}
    {% block js %}
    <script src="{% static 'js/form-validation.js' %}"></script>
    {% endblock %}
</head>
<body class="text-center bg-light">
<div class="container">
    {% block container %}
    {% endblock %}
</div>
</body>
</html>

authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load static %}
{% load my_tags %}
{% block css %}
<link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/registration.css' %}">
{% endblock %}
{% block container %}
<div class="py-5 text-center">
    <a class="h1 mb-3 font-weight-bold text-dark" href="{% url 'main:index' %}">Xabr</a>
    <h2>Редактрирование профиля</h2>
</div>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for error in login_form.non_field_errors %}
    <div class="alert alert-danger">
        <strong>{{ error|escape }}</strong>
    </div>
    {% endfor %}
    <div class="media">
        <img class="mr-3 mt-2 " src="{{ user.avatar|media_folder_users }}" alt="">
        <div class="media-body">
            <div class="form-group">
                <label for="{{ edit_form.username.id_for_label }}">Login</label>
                <div tabindex="0" class="" role="button" data-bs-toggle="popover"
                     data-bs-trigger="focus" title="Login изменять нельзя"
                >{{ edit_form.username }}
                </div>
            </div>
            <div class="form-group">
                <label for="{{ edit_form.first_name.id_for_label }}">Имя</label>
                {{ edit_form.first_name }}
                {{ edit_form.first_name.errors }}
            </div>
            <div class="form-group">
                <label for="{{ edit_form.email.id_for_label }}">Email</label>
                {{ edit_form.email }}
                {% for error in edit_form.email.errors %}
                <div id="emailHelp" class="form-text"> {{ error }}</div>
                {% endfor %}
            </div>
            <div class="form-group">
                <label for="{{ edit_form.age.id_for_label }}">Возраст</label>
                {{ edit_form.age }}
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="{{ edit_form.aboutMe.id_for_label }}">О себе</label>
        {{ edit_form.aboutMe }}
    </div>
    <div class="form-group">
        <label for="{{ edit_form.avatar.id_for_label }}">Добавить фото</label>
        {{ edit_form.avatar }}
    </div>
    <input class="btn btn-lg btn-primary btn-block form-control" type="submit" value="Сохранить">
</form>
<a class="mt-1 btn btn-lg btn-primary form-control" href="{% url 'main:index' %}">
    На главную
</a>
<a class="mt-1 btn btn-lg btn-primary form-control" href="{% url 'auth:read_profile' %}">
    В профиль
</a>
<footer class="mt-4 text-muted text-center text-small">
    <p class="mb-1">&copy; 2020-{% now 'Y' %} Команда №1</p>
</footer>
{% endblock %}

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block css %}
<link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
<meta name="theme-color" content="#563d7c">
<link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/signin.css' %}">
{% endblock %}
{% block container %}
<form class="form-horizontal form-signin" method="post">
    <a class="h1 mb-3 font-weight-bold text-dark" href="{% url 'main:index' %}">Xabr</a>
    <h1 class="h3 mb-3 font-weight-normal">Пожалуйста авторизируйтесь</h1>
    {% csrf_token %}
    {% for error in login_form.non_field_errors %}
    <div class="alert alert-danger">
        <strong>{{ error|escape }}</strong>
    </div>
    {% endfor %}
    <div class="form-group">
        <label for="{{ login_form.username.id_for_label }}"></label>
        {{ login_form.username }}
    </div>
    <div class="form-group">
        <label for="{{ login_form.password.id_for_label }}"></label>
        {{ login_form.password }}
    </div>
    <br>
    <label>
        <input type="checkbox" value="remember-me"> Запомнить меня
    </label>
    <input class="form-control btn btn-lg btn-primary btn-block" type="submit" value="Войти">
    <a href="{% url 'auth:register' %}?next={{ request.path }}"
       class="btn  btn-lg btn-primary btn-block">
        Зарегистрироваться
    </a>
    {% if next == '/auth/register/' %}
    <a href="{% url 'main:index' %}"
       class="btn  btn-lg btn-primary btn-block">
        Вернуться на главную
    </a>
    {% else %}
    <a href="{{ next }}"
       class="btn  btn-lg btn-primary btn-block">
        Вернуться назад
    </a>
    {% endif %}
    <p class="mt-4 mb-3 text-muted">&copy; 2020-{% now 'Y' %} Команда №1</p>
</form>
{% endblock %}

authapp/templates/authapp/read_profile.html
{% extends 'authapp/base.html' %}
{% load static %}
{% load my_tags %}
{% block css %}
<link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/registration.css' %}">
{% endblock %}
{% block container %}
<div class="py-5">
    <a class="h1 mb-3 font-weight-bold text-dark" href="{% url 'main:index' %}">Xabr</a>
    <h2>Профиль</h2>
</div>
<div class="media">
    <img class="mr-3 " src="{{ user.avatar|media_folder_users }}" alt="">
    <div class="media-body">
        <form>
            <div class="form-group">
                <label for="username">Login</label>
                <input type="text" class="form-control text-dark" id="username"
                       placeholder="{{ user.username|title }}">
            </div>
            {% if user.first_name %}
            <div class="form-group">
                <label for="first_name">Имя</label>
                <input type="text" class="form-control text-dark" id="first_name"
                       placeholder="{{ user.first_name|title }}">
            </div>
            {% endif %}
            {% if user.last_name %}
            <div class="form-group">
                <label for="last_name">Фамилия</label>
                <input type="text" class="form-control" id="last_name"
                       placeholder="{{ user.last_name|title }}">
            </div>
            {% endif %}
            <div class="form-group">
                <label for="staticEmail">Email</label>
                <input type="text" class="form-control text-dark" id="staticEmail"
                       placeholder="{{ user.email }}">
            </div>
            {% if user.age %}
            <div class="form-group">
                <label for="age">Возраст</label>
                <input type="text" class="form-control" id="age"
                       placeholder="{{ user.age }}">
            </div>
            {% endif %}
        </form>
    </div>
</div>
{% if user.aboutMe %}
<div class="form-group">
    <label for="aboutMe">О себе</label>
    <input type="text" class="form-control" id="aboutMe"
           placeholder="{{ user.aboutMe }}">
</div>
{% endif %}
<a class="btn btn-lg btn-primary form-control" href="{% url 'auth:edit' %}">
    Редактировать профиль
</a>
<a class="mt-1 btn btn-lg btn-primary form-control" href="{% url 'main:index' %}">
    На главную
</a>
<footer class="my-4 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2020-{% now 'Y' %} Команда №1</p>
</footer>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block css %}
<link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/registration.css' %}">
{% endblock %}
{% block container %}
<div class="py-5 text-center">
    <a class="h1 mb-3 font-weight-bold text-dark" href="{% url 'main:index' %}">Xabr</a>
    <h2>Регистрация</h2>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal" action="{% url 'auth:register' %}" method="post"
              enctype="multipart/form-data">
            {% csrf_token %}
            {{ register_form.as_p }}
            <br>
            <input class="form-control btn  btn-lg btn-primary btn-block" type="submit" value="Зарегистрироваться">
            <a href="{{ next }}?next={{ request.path }}"
               class="btn  btn-lg btn-primary btn-block">
                Вернуться назад
            </a>
        </form>
    </div>
</div>
<footer class="my-4 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2020-{% now 'Y' %} Команда №1</p>
</footer>
{% endblock %}

authapp/templates/authapp/send_confirm.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block css %}
<link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
<meta name="theme-color" content="#563d7c">
<link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/signin.css' %}">
{% endblock %}
{% block container %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong> Сообщение подтверждения отправлено! </strong>
    Проверьте письмо на почте и перейдите по ссылке указанной в письме.
    <a type="button" class="close" data-dismiss="alert" aria-label="Close" href="{% url 'main:index' %}"><span
            aria-hidden="true">&times;</span></a>
    <hr>
    <a type="button" class="text-muted" href="{% url 'main:index' %}">
        На главную</a>
</div>
<br>
<br>
{% endblock %}

authapp/templates/authapp/verification.html
{% extends 'authapp/base.html' %}
{% load static %}
{% block css %}
<link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
<meta name="theme-color" content="#563d7c">
<link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/signin.css' %}">
{% endblock %}
{% block container %}
{% if user.is_authenticated %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong> Поздравляем! </strong>
    Пользователь {{ user.username }} подтвержден.
    <a type="button" class="close" data-dismiss="alert" aria-label="Close" href="{% url 'main:index' %}">
        <span aria-hidden="true">&times;</span>
    </a>
</div>
{% else %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong> Верификация не пройдена. </strong>
    <a type="button" class="close" data-dismiss="alert" aria-label="Close" href="{% url 'main:index' %}"><span
            aria-hidden="true">&times;</span></a>
    <hr>
    <a type="button" class="text-muted" href="{% url 'main:index' %}">
        На главную</a>
</div>
{% endif %}
{% endblock %}