blogapp/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView
from django.contrib.auth.decorators import login_required

app_name = 'blog'

urlpatterns = [
    path('post/<slug:slug>/edit/', login_required(BlogUpdateView.as_view()), name='post_edit'),
    path('post/new/', login_required(BlogCreateView.as_view()), name='post_new'),
    path('post/<slug:slug>/', login_required(BlogDetailView.as_view()), name='post_detail'),
    path('post/', login_required(BlogListView.as_view()), name='post_list'),
    path('post/<slug:slug>/delete/', login_required(BlogDeleteView.as_view()), name='post_delete'),
]

xabr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from xabr import settings

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('blog/', include('blogapp.urls', namespace='blogapp')),
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/models.py
from django.db import models

mainapp/models.py
from django.db import models
from django.urls import reverse
from authapp.models import XabrUser
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.template import defaultfilters
import random
import string

from unidecode import unidecode

MD = 'MD'
STATUS_CHOICES = (
    ('True', 'Опубликована'),
    ('MD', 'На модерации'),
    ('False', 'Черновик'),
)


class Category(models.Model):
    """модель категории поста"""

    name = models.CharField(verbose_name='название категории', max_length=64, default='', unique=True)
    slug = models.SlugField(verbose_name='уникальный адрес', max_length=70)
    description = models.TextField(verbose_name='описание категории', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"

    def __str__(self):
        return self.name


class Post(models.Model):
    """модель статьи"""

    user = models.ForeignKey(XabrUser, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, verbose_name='категория', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='название статьи', max_length=128)
    slug = models.SlugField(verbose_name='уникальный адрес', max_length=70, unique=True)
    description = models.TextField(verbose_name='краткое описание статьи', blank=True)
    posts_text = models.TextField(verbose_name='текст статьи', blank=True)
    create_datetime = models.DateTimeField(verbose_name='дата создания', auto_now_add=True, blank=True)
    like_quantity = models.PositiveIntegerField('кол-во', default=0)
    is_active = models.CharField(verbose_name='статус', max_length=128, choices=STATUS_CHOICES)
    comment = models.TextField(verbose_name='комментарии', blank=True)

    class Meta:
        verbose_name = "пост"
        verbose_name_plural = "посты"
        ordering = ('-create_datetime',)

    def __str__(self):
        return f"{self.name} ({self.category.name} {self.is_active} {self.slug})"

    def get_absolute_url(self):
        return reverse('blogapp:post_list')


def random_string_generator(size=10, chars=string.ascii_lowercase + string.digits):
    """функция, генерирующая набор случайных строковых символов"""

    return ''.join(random.choice(chars) for _ in range(size))


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    """функция получения и сохранения уникального slug"""

    if instance.slug:
        instance.slug = instance.slug
    else:
        slug = defaultfilters.slugify(unidecode(instance.name))
        slugs = Post.objects.filter()
        for slug_old in slugs.values("slug"):
            if slug in slug_old["slug"]:
                instance.slug = "%s-%s" % (slug, random_string_generator(size=4))
                break
            else:
                instance.slug = slug


pre_save.connect(pre_save_post_receiver, sender=Post)


class Comments(models.Model):
    """модель комментариев к постам"""

    user = models.ForeignKey(XabrUser, verbose_name="пользователь", related_name="comments", on_delete=models.CASCADE)
    post = models.ForeignKey(Post, verbose_name="пост", on_delete=models.CASCADE)
    text = models.TextField("комментировать")
    created = models.DateTimeField("дата добавления", auto_now_add=True, null=True)
    moderation = models.BooleanField("модерация", default=False)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = "комментарий"
        verbose_name_plural = "комментарии"
        ordering = ('-created',)

    def __str__(self):
        return f"{self.user}"


class Like(models.Model):
    """модель лайков к постам"""

    user = models.ForeignKey(XabrUser, on_delete=models.CASCADE)
    slug = models.SlugField(verbose_name='URL', max_length=70, default='')
    is_active = models.BooleanField(verbose_name='активна', default=True)

    class Meta:
        verbose_name = "лайк"
        verbose_name_plural = "лайки"

blogapp/views.py
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from mainapp.models import Post


class BlogListView(ListView):
    """класс для вывода списка всех статей пользователя"""

    model = Post
    template_name = 'post_list.html'


class BlogDetailView(DetailView):
    """класс для вывода черновиков пользователя"""

    model = Post
    template_name = 'post_detail.html'


class BlogCreateView(CreateView):
    """класс для вывода страницы создания новой статьи пользователем"""

    model = Post
    template_name = 'post_new.html'
    fields = ['user', 'category', 'name', 'description', 'posts_text', 'is_active']


class BlogUpdateView(UpdateView):
    """класс для вывода страницы редактирования статьи/черновика пользователем"""

    model = Post
    template_name = 'post_edit.html'
    fields = ['category', 'name', 'description', 'posts_text', 'is_active']


class BlogDeleteView(DeleteView):
    """класс для вывода страницы удаления статьи/черновика пользователем"""

    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('blog:post_list')

blogapp/templates/post_delete.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}
{% block main %}
<div class="mt-3 posts text-left">
    <h3 class="text-center"> Удалить статью: </h3>
    <div class="card ">
        <div class="card-header">
            Категория: {{ object.category }}
        </div>
        <div class="card-body">
            <h5 class="card-title">Название статьи: <a href="#">{{ object.name }}</a></h5>
            <footer class="blockquote-footer">Статья создана <cite title="Source Title">{{ object.create_datetime }}
            </cite></footer>
            <p class="card-text">Краткое описание статьи: {{ object.description }}</p>
            <p class="card-text">Текст статьи: {{ object.posts_text }}</p>
            <div class="btn-group" role="group" aria-label="Basic example">
                <form action="" method="post">{% csrf_token %}
                    <h3>Вы уверены, что хотите удалить "{{ post.name }}"?</h3>
                    <input class="btn btn-secondary bg-danger" type="submit" value="Подтвердить удаление"/>
                    <a type="button" class="btn btn-secondary"
                       href="{% url 'blog:post_detail' object.slug %}">Вернуться</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blogapp/templates/post_detail.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}
{% block main %}
<div class="mt-3 posts text-left">
    <h3 class="text-center"> Ваша статья: </h3>
    <div class="card ">
        <div {% if object.is_active == "True" %}
             class="card-header bg-success"
             {% endif %}
             {% if object.is_active == "MD" %}
             class="card-header bg-warning"
             {% else %}
             class="card-header bg-danger"
             {% endif %}>
            Статус: {{ object.is_active }}
        </div>
        <div class="card-header">
            Категория: {{ object.category }}
        </div>
        <div class="card-body">
            <h5 class="card-title">Название статьи: <a href="#">{{ object.name }}</a></h5>
            <footer class="blockquote-footer">Статья создана <cite title="Source Title">{{ object.create_datetime }}
            </cite></footer>
            <p class="card-text">Краткое описание статьи: {{ object.description }}</p>
            <p class="card-text">Текст статьи: {{ object.posts_text }}</p>
            <div class="btn-group" role="group" aria-label="Basic example">
                <a type="button" class="btn btn-secondary"
                   href="{% url 'blog:post_list' %}">Все статьи</a>
                <a type="button" class="btn btn-secondary"
                   href="{% url 'blog:post_edit' object.slug %}">Редактировать статью</a>
                <a type="button" class="btn btn-secondary"
                   href="{% url 'blog:post_delete' object.slug %}">Удалить статью</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blogapp/templates/post_edit.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}
{% block main %}
<div class="mt-3 posts text-left">
    <h3 class="text-center"> Редактировать статью:</h3>
    <div class="card ">
        <div class="card-header">
            <form action="" method="post">{% csrf_token %}
                <div class="form-group">
                    <p class="card-title"><label for="{{object.category}}">Категория:</label> <select
                            name="category" required
                            id="id_category">
                        <option value="{{object.category.id}}" selected>{{object.category}}</option>
                    </select></p>
                </div>
                <p class="card-text"><label for="id_name">Название статьи:</label></p>
                <input type="text" class="form-control text-dark text" name="name" value="{{ object.name }}"
                       maxlength="128"
                       required=""
                       id="object.name.id">
                <p class="card-text"><label for="id_description">Краткое описание статьи:</label>
                    <textarea name="description" style="width: 100%; height: 150px;" id="id_description">{{ object.description }}
                </textarea></p>
                <p class="card-text"><label for="id_posts_text">Текст статьи:</label>
                    <textarea name="posts_text" style="width: 100%; height: 400px;" id="id_posts_text"> {{ object.posts_text }}
                </textarea></p>
                <p class="card-text">{{ form.errors }}</p>
                {% if object.is_active == "True" %}
                <p class="card-text">Статус: Опубликована </p>
                <input class="card-text" type="radio" name="is_active" value="False"> Черновик</p>
                <input class="card-text" type="radio" name="is_active" value="MD"> На модерацию</p>
                {% endif %}
                {% if object.is_active == "MD" %}
                <p class="card-text">Статус: На модерацию </p>
                <input class="card-text" type="radio" name="is_active" value="False"> Черновик</p>
                {% endif %}
                {% if object.is_active == "False" %}
                <p class="card-text">Статус: Черновик </p>
                <input class="card-text" type="radio" name="is_active" value="False"> Черновик</p>
                <input class="card-text" type="radio" name="is_active" value="MD"> На модерацию</p>
                {% endif %}
                <div class="btn-group" role="group" aria-label="Basic example">
                    <input class="btn btn-secondary" type="submit" value="Обновить"/>
                </div>
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a type="button" class="btn btn-secondary"
                       href="{% url 'blog:post_list' %}">Назад</a>
                    <a type="button" class="btn btn-secondary"
                       href="{% url 'blog:post_detail' object.slug %}">Смотреть статью</a>
                    <a type="button" class="btn btn-secondary"
                       href="{% url 'blog:post_delete' object.slug %}">Удалить статью</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blogapp/templates/post_list.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}
{% block main %}
<div class="mt-3 posts text-left">
    <h3 class="text-center"> Ваши статьи на Xabr:</h3>
    <div class="btn-group text-center" role="group" aria-label="Basic example">
        <a type="button" class="btn btn-secondary bg-success"
           href="{% url 'blog:post_new' %}">Написать статью</a>
    </div><br><br>
    {% for object in object_list %}
    {% if object.user.first_name == request.user.first_name%}
    <div class="card ">
        <div {% if object.is_active == "True" %} class="card-header bg-success" {% endif %}
        {% if object.is_active == "MD" %} class="card-header bg-warning"
        {% else %} class="card-header bg-danger"
        {% endif %}> Статус: {{ object.is_active }}
    </div>
    <div class="card-header">
        Категория: {{ object.category }}
    </div>
    <div class="card-body">
        <h5 class="card-title">{{ object.name }}</h5>
        <footer class="blockquote-footer">Статья создана <cite title="Source Title">{{ object.create_datetime }}
        </cite></footer>
        <p class="card-text"> {{ object.description }}</p>
        <div class="btn-group" role="group" aria-label="Basic example">
            <a type="button" class="btn btn-secondary"
               href="{% url 'blog:post_detail' object.slug %}">Смотреть статью</a>
            <a type="button" class="btn btn-secondary"
               href="{% url 'blog:post_edit' object.slug %}">Редактировать статью</a>
            <a type="button" class="btn btn-secondary"
               href="{% url 'blog:post_delete' object.slug %}">Удалить статью</a>
        </div>
    </div>
</div>
{% endif %}
{% endfor %}
</div>
{% endblock %}

blogapp/templates/post_new.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}
{% block main %}
<div class="mt-3 posts text-left">
    <h3 class="text-center"> Новая статья:</h3>
    <div class="card ">
        <div class="card-header">
            <form action="" method="post">{% csrf_token %}
                <div class="form-group">
                    <p class="card-text d-none">user:<select name="user" required="" id="id_user">
                        <option value="{{request.user.id}}">{{request.user.username}}</option>
                    </select></p>
                    <p class="card-text">Категория: {{ form.category }}</p>
                    <p class="card-text">Название статьи:{{ form.name }}</p>
                    <p class="card-text">Краткое описание статьи:{{ form.description }}</p>
                    <p class="card-text">Текст статьи:{{ form.posts_text }}</p>
                    <p class="card-text">{{ form.errors }}</p>
                    {% if form.is_active %}
                    <input class="card-text" type="radio" name="is_active" value="False" checked> Черновик</p>
                    <input class="card-text" type="radio" name="is_active" value="MD"> На модерацию</p>
                    {% endif %}
                </div>
                <div class="btn-group" role="group" aria-label="Basic example">
                    <input class="btn btn-secondary" type="submit" value="Сохранить"/>
                    <a type="button" class="btn btn-secondary"
                       href="{% url 'blog:post_list' %}">Все статьи</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}