authapp/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('read_profile/', authapp.read_profile, name='read_profile'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
    path('send/mail/confirm/', TemplateView.as_view(template_name='authapp/send_confirm.html'), name='send_confirm'),
]

mainapp/urls.py
import mainapp.views as mainapp
from django.urls import path

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('post/<slug:slug>/', mainapp.post, name='post'),
    path('help/', mainapp.help, name='help'),
    path('category/<slug:slug>/', mainapp.category_page, name='category_page'),
    path('changelike/<slug:slug>/', mainapp.change_like, name='change_like'),
    path('search/', mainapp.SearchResultsView.as_view(), name='search_results'),
    path('delete/comment/', mainapp.delete_comment, name='delete_comment'),
    path('to/banish/', mainapp.to_banish, name='to_banish'),
]

xabr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from xabr import settings

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('blog/', include('blogapp.urls', namespace='blogapp')),
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models
from django.urls import reverse
from authapp.models import XabrUser
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.template import defaultfilters
import random
import string

from unidecode import unidecode

MD = 'MD'
STATUS_CHOICES = (
    ('True', 'Опубликована'),
    ('MD', 'На модерации'),
    ('False', 'Черновик'),
)


class Category(models.Model):
    """модель категории поста"""

    name = models.CharField(verbose_name='название категории', max_length=64, default='', unique=True)
    slug = models.SlugField(verbose_name='уникальный адрес', max_length=70)
    description = models.TextField(verbose_name='описание категории', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"

    def __str__(self):
        return self.name


class Post(models.Model):
    """модель статьи"""

    user = models.ForeignKey(XabrUser, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, verbose_name='категория', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='название статьи', max_length=128)
    slug = models.SlugField(verbose_name='уникальный адрес', max_length=70, unique=True)
    description = models.TextField(verbose_name='краткое описание статьи', blank=True)
    posts_text = models.TextField(verbose_name='текст статьи', blank=True)
    create_datetime = models.DateTimeField(verbose_name='дата создания', auto_now_add=True, blank=True)
    like_quantity = models.PositiveIntegerField('кол-во', default=0)
    is_active = models.CharField(verbose_name='статус', max_length=128, choices=STATUS_CHOICES)
    comment = models.TextField(verbose_name='комментарии', blank=True)

    class Meta:
        verbose_name = "пост"
        verbose_name_plural = "посты"
        ordering = ('-create_datetime',)

    def __str__(self):
        return f"{self.name} ({self.category.name} {self.is_active} {self.slug})"

    def get_absolute_url(self):
        return reverse('blogapp:post_list')


def random_string_generator(size=10, chars=string.ascii_lowercase + string.digits):
    """функция, генерирующая набор случайных строковых символов"""

    return ''.join(random.choice(chars) for _ in range(size))


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    """функция получения и сохранения уникального slug"""

    if instance.slug:
        instance.slug = instance.slug
    else:
        slug = defaultfilters.slugify(unidecode(instance.name))
        slugs = Post.objects.filter()
        for slug_old in slugs.values("slug"):
            if slug in slug_old["slug"]:
                instance.slug = "%s-%s" % (slug, random_string_generator(size=4))
                break
            else:
                instance.slug = slug


pre_save.connect(pre_save_post_receiver, sender=Post)


class Comments(models.Model):
    """модель комментариев к постам"""

    user = models.ForeignKey(XabrUser, verbose_name="пользователь", related_name="comments", on_delete=models.CASCADE)
    post = models.ForeignKey(Post, verbose_name="пост", on_delete=models.CASCADE)
    text = models.TextField("комментировать")
    created = models.DateTimeField("дата добавления", auto_now_add=True, null=True)
    moderation = models.BooleanField("модерация", default=False)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = "комментарий"
        verbose_name_plural = "комментарии"
        ordering = ('-created',)

    def __str__(self):
        return f"{self.user}"


class Like(models.Model):
    """модель лайков к постам"""

    user = models.ForeignKey(XabrUser, on_delete=models.CASCADE)
    slug = models.SlugField(verbose_name='URL', max_length=70, default='')
    is_active = models.BooleanField(verbose_name='активна', default=True)

    class Meta:
        verbose_name = "лайк"
        verbose_name_plural = "лайки"

mainapp/forms.py
from django import forms
from django.forms import Textarea
from mainapp.models import Comments


class CommentForm(forms.ModelForm):
    """форма комментариев к статьям"""

    class Meta:
        model = Comments
        fields = ('text',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
        self.fields['text'].widget = Textarea(attrs={'rows': 2})

mainapp/views.py
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView

from authapp.models import XabrUser
from .forms import CommentForm
from .models import Category, Post, Comments, Like


class SearchResultsView(ListView):
    """контроллер, возврящающий страницу с результатами поиска"""

    model = Post
    template_name = 'search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('search')
        object_list = Post.objects.filter(
            Q(
                is_active__icontains=True) & Q(
                name__icontains=query) | Q(
                is_active__icontains=True) & Q(
                posts_text__icontains=query)).order_by(
            '-like_quantity',
            '-create_datetime')
        return object_list



def index(request):
    """контроллер, возврящающий главную страницу со списком всех статей сайта"""

    posts = Post.objects.filter(is_active=True).order_by('-create_datetime')
    categories = Category.objects.filter(is_active=True)

    context = {
        'page_title': 'главная',
        'posts': posts,
        'categories': categories,
    }
    return render(request, 'mainapp/index.html', context)


def post(request, slug):
    """контроллер вывода полной статьи"""

    post = Post.objects.filter(slug=slug, is_active=True)
    categories = Category.objects.all()
    comment = Comments.objects.filter(post=post.first())

    if request.method == "POST":
        form = CommentForm(data=request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.post = post.first()
            form.save()

    else:
        form = CommentForm()

    context = {
        'page_title': 'хабр',
        'posts': post,
        'categories': categories,
        'comments': comment,
        'form': form,
    }
    return render(request, 'mainapp/post.html', context)


def help(request):
    """контроллер вывода страницы "Помощь" """

    categories = Category.objects.filter(is_active=True)

    context = {
        'page_title': 'помощь',
        'categories': categories
    }
    return render(request, 'mainapp/help.html', context)


def category_page(request, slug):
    """контроллер вывода страниц статей, относящихся к конкретной категории """

    categories = Category.objects.filter(is_active=True)

    if request.user.is_authenticated:
        new_like, created = Like.objects.get_or_create(
            user=request.user, slug=slug)
    else:
        new_like = Like.objects.all()
    if slug == '':
        category = {'slug': '', 'name': 'все'}
        posts = Post.objects.filter(
            is_active=True).order_by('-create_datetime')
    else:
        category = get_object_or_404(Category, slug=slug)
        posts = category.post_set.filter(
            is_active=True).order_by('-create_datetime')

    context = {
        'page_title': 'главная',
        'categories': categories,
        'category': category,
        'posts': posts,
        'new_like': new_like,
    }
    return render(request, 'mainapp/category_page.html', context)


def change_like(request, slug):
    """функция проставления лайка/дизлайка"""

    post = get_object_or_404(Post, slug=slug)
    new_like, created = Like.objects.get_or_create(
        user=request.user, slug=slug)

    if request.method == 'POST':
        new_like.is_active = not new_like.is_active
        if not new_like.is_active:
            post.like_quantity += 1
            post.save()
            new_like.save()
        else:
            post.like_quantity -= 1
            post.save()
            new_like.save()
        context = {
            'new_like': new_like,
        }

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'), context)


def delete_comment(request):
    """функция удаления комментария к статье"""

    id = request.POST['comment_id']
    if request.method == 'POST':
        comment = get_object_or_404(Comments, id=id)
        comment.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def to_banish(request):
    """функция, позволяющая забанить пользователя администратору/модератору"""

    user_com = request.POST['user_id']
    if request.method == 'POST':
        block_user = XabrUser.objects.get(username=user_com)
        block_user.is_active = False
        block_user.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def doc(request):
    """контроллер вывода страницы "Документация" """

    return render(request, 'doc/index.html')

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        {% block title %}
            {{ page_title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/font-awesome/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <style type="text/css">
            #id_name, #id_slug {
                width: 100%;
            }

            #id_description {
                width: 100%;
                height: 150px;
            }

            #id_posts_text {
                width: 100%;
                height: 400px;
            }
        </style>
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/common.js' %}"></script>
    {% endblock %}
</head>
<body>
    <div class="wrapper">
        <div class="content">
            <header>
                {% include 'mainapp/includes/inc__header.html' %}
                {% include 'mainapp/includes/inc__main_menu.html' %}
            </header>
            <main role="main" class="flex-shrink-0">
                <div class="container">
                    {% block main %}
                    {% endblock %}
                </div>
            </main>
        </div>
        <footer class="footer blog-footer text-center mt-auto py-3">
            {% block footer %}
                <div class="container">
                    <p>&copy; 2020-{% now 'Y' %} Команда №1 </p>
                    <a class="text-muted" href="{% url 'main:help' %}">Помощь</a>
                </div>
            {% endblock %}
        </footer>
    </div>
</body>
</html>

mainapp/templates/mainapp/category_page.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block main %}
<div class="row">
    <div class="col-md-12">
        <h3 class="pb-4 mb-4 blog-main font-italic border-bottom">
            {{ category.name }}
        </h3>
        {% for post in posts %}
        <div class="blog-post">
            <h1 class="blog-post-title"><a href="{% url 'main:post' post.slug %}">{{ post.name }}</a></h1>
            <p class="blog-post-meta">{{ post.create_datetime }} автор: {{ post.user|title }}</p>
            <p>{{ post.description }}</p>
            <nav class="blog-pagination">
                <form action="{% url 'main:change_like' post.slug %}" method="post">
                    <a class="btn btn-outline-primary" href="{% url 'main:post' post.slug %}">Читать далее</a>
                    {% if user.is_authenticated %}
                    <a class="btn btn-outline-primary" href="{% url 'main:post' post.slug %}" tabindex="-1"
                       aria-disabled="true">Комментировать</a>
                    {% csrf_token %}
                    {% if new_like.is_active %}
                    <button class="btn btn-outline-primary"><i class="fa fa-heart"
                                                               aria-hidden="true"></i>
                        {{ post.like_quantity }}
                    </button>
                    {% else %}
                    <button class="btn btn-outline-primary"><i class="fa fa-heart-o"
                                                               aria-hidden="true"></i>
                        {{ post.like_quantity }}
                    </button>
                    {% endif %}
                    {% else %}
                    <a class="btn btn-outline-primary" href="{% url 'auth:login' %}?next={{ request.path }}"
                       tabindex="-1"
                       aria-disabled="true">Комментировать</a>
                    <a class="btn btn-outline-primary"
                       href="{% url 'auth:login' %}?next={{ request.path }}"><i
                            class="fa fa-heart" aria-hidden="true"></i>{{ post.like_quantity }}</a>
                    {% endif %}
                </form>
            </nav>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/help.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block main %}
    <h3 class="pb-4 mb-4 font-italic border-bottom">Помощь</h3>
    <h2 class="blog-post-title">Доступные механики на сайте</h2><br>
    <div class="blog-post">
        <p>На сайте реализованы следующие роли:<br>
            - незарегистрированный пользователь (может только просматривать контент);<br>
            - зарегистрированный пользователь (может создавать/редактировать свои статьи и оставлять комментарии);<br>
            - модератор (может создавать/удалять статьи и комментарии, а также блокировать/удалять пользователей);<br>
            - администратор - полный доступ к функционалу сайта, в т.ч. назначение и удаление модераторов.<br>
        </p>
    </div><br><br>
    <h2 class="blog-post-title">В данный момент доступны следующие cценарии</h2><br>
    <h3 class="blog-post-title">Сценарий №1</h3>
    <div class="blog-post">
        <p> Незарегистрированный пользователь заходит на сайт, просматривает главную страницу, выбирает интересующую
            его статью. Хочет оставить комментарий, но не может, так как требуется регистрация. Сайт предлагает ему
            зарегистрироваться или авторизоваться. Незарегистрированный пользователь вводит свои данные для
            регистрации, сохраняет их и далее логин-пароль. Зарегистрированный пользователь сразу вводит
            логин-пароль. После этого возвращается на ту самую статью, ставит ей лайк и/или оставляет под
            ней комментарий.
        </p>
    </div><br>
    <h3 class="blog-post-title">Сценарий №2</h3>
    <div class="blog-post">
        <p> Зарегистрированный пользователь X хочет написать статью. Он логинится с любой страницы сайта и в
            своем личном кабинете, у него появляется кнопка “Создать статью”. Он выбирает раздел к которому
            статья будет относиться, выбирает теги, пишет статью, нажимает на кнопку “Загрузить статью”.
        </p>
    </div><br>
    <h2 class="blog-post-title">Будут доступны cценарии</h2><br>
    <h3 class="blog-post-title">Сценарий №3</h3>
    <div class="blog-post">
        <p> Пользователь заходит на сайт под своим профилем (может оставлять комментарии и т.п.) и видит
            статью/комментарий с рекламой онлайн-казино. Пользователь оставляет комментарий, начинающийся
            с @moderator и причиной призыва модератора. Все модераторы получают уведомление в личном кабинете
            о призыве модератора с ссылкой на статью/комментарий.
        </p>
    </div><br>
    <h3 class="blog-post-title">Сценарий №4</h3>
    <div class="blog-post">
        <p> Модератор заходит на сайт, логинится с любой страницы сайта и видит в одной из статей много
            одинаковых рекламных комментариев онлайн-казино. Модератор удаляет комментарии и блокирует
            пользователя, оставившего рекламные комментарии на 2 недели. Заблокированный пользователь видит
            в своем личном кабинете уведомление о том, что он нарушил правила пользования сайтом и больше
            не может писать статьи, оставлять комментарии и ставить лайки в течение следующих 2 недель.
        </p>
    </div><br><br>
    <h2 class="blog-post-title">Доступный функционал сайта</h2><br>
    <div class="blog-post">
        <p>На сайте реализован функционал регистрации и авторизации пользователей.
            У зарегистрированных пользователей есть возможность не просто читать хабы, но оставлять
            комментарии к ним.<br><br>
            В личном кабинете пользователь при желании может заполнить/поменять информацию о себе: имя,
            возраст, краткое описание.<br><br>
            У зарегистрированных пользователей есть возможность ставить лайки статьям,
            комментариям. Позже на основе этих лайков сформирована система рейтингов
            для статей, комментариев и авторов.<br><br>
            Также на сайте есть расширенный поиск по сайту для всех пользователей. В поиске позже появится
            фильтр по дате (“сначала свежие”) и по рейтингу (“сначала с самым высоким рейтингом”).
        </p>
    </div><br><br>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block main %}
<div class="row">
    <div class="col-md-12 ">
        <h3 class="pb-4 mb-4 blog-main font-italic border-bottom">
            Последние публикации
        </h3>
        {% for post in posts %}
        <div class="blog-post">
            <h1 class="blog-post-title"><a href="{% url 'main:post' post.slug %}">{{ post.name }}</a></h1>
            <p class="blog-post-meta">{{ post.create_datetime }} автор: {{ post.user|title }}</p>
            <p>{{ post.description }}</p>
            <nav class="blog-pagination">
                <form action="{% url 'main:change_like' post.slug %}" method="post">
                    <a class="btn btn-outline-primary" href="{% url 'main:post' post.slug %}">Читать далее</a>
                    {% if user.is_authenticated %}
                    <a class="btn btn-outline-primary" href="{% url 'main:post' post.slug %}" tabindex="-1"
                       aria-disabled="true">Комментировать</a>

                    {% csrf_token %}
                    {% if new_like.is_active %}
                    <button class="btn btn-outline-primary"><i class="fa fa-heart"
                                                               aria-hidden="true"></i>
                        {{ post.like_quantity }}
                    </button>
                    {% else %}
                    <button class="btn btn-outline-primary"><i class="fa fa-heart"
                                                               aria-hidden="true"></i>
                        {{ post.like_quantity }}
                    </button>
                    {% endif %}

                    {% else %}
                    <a class="btn btn-outline-primary" href="{% url 'auth:login' %}?next={{ request.path }}"
                       tabindex="-1" aria-disabled="true">Комментировать</a>
                    <a class="btn btn-outline-primary"
                       href="{% url 'auth:login' %}?next={{ request.path }}"><i
                            class="fa fa-heart" aria-hidden="true"></i>{{ post.like_quantity }}</a>
                    {% endif %}
                </form>
            </nav>

        </div>

        {% endfor %}

    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/post.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block main %}
<div class="row">
    <div class="col-md-12">
        {% for post in posts %}
        <h3 class="pb-4 mb-4 blog-main font-italic border-bottom">
            {{ post.category }}
        </h3>
        <div class="blog-post">
            <h1 class="blog-post-title">{{ post.name }}</h1>
            <p class="blog-post-meta">{{ post.create_datetime }} автор: {{ post.user|title }}</p>
            <hr>
            <p>{{ post.posts_text }}</p>
            <nav class="blog-pagination">
                <form action="{% url 'main:change_like' post.slug %}" method="post">
                    {% if user.is_authenticated %}
                    {% csrf_token %}
                    {% if new_like.is_active %}
                    <button class="btn btn-outline-primary"><i class="fa fa-heart"
                                                               aria-hidden="true"></i>{{ post.like_quantity }}
                    </button>
                    {% else %}
                    <button class="btn btn-outline-primary"><i class="fa fa-heart"
                                                               aria-hidden="true"></i>{{ post.like_quantity }}
                    </button>
                    {% endif %}
                </form>
                <hr>
                {% for comment in comments %}
                <footer class="blockquote-footer">автор:{{ comment.user }} <cite
                        title="Source Title">
                    {{ comment.created }}</cite></footer>
                <br>
                <p class="card-text"> {{ comment.text }}</p>
                {% if comment.user == request.user or user.is_superuser or user.is_staff %}
                <form action="{% url 'main:delete_comment' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="comment_id" value="{{ comment.id }}"/>
                    <button class="btn btn-outline-primary"> удалить </button>
                </form>
                <br>
                {% endif %}
                {% if comment.user.is_active %}
                {% if user.is_superuser or user.is_staff %}
                <form action="{% url 'main:to_banish' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="comment_id" value="{{ comment.id }}"/>
                    <input type="hidden" name="user_id" value="{{ comment.user }}"/>
                    <button class="btn btn-outline-primary">Забанить</button>
                </form>
                {% endif %}
                {% endif %}
                <br>
                {% endfor %}
                <hr>
                <form class="form_comment" action="" method="post">
                    {{ form.as_p }}
                    {% csrf_token %}
                    <p><input class="btn btn-outline-primary float-left" type="submit" value="Добавить"></p>
                </form>
                {% else %}
                <a class="btn btn-outline-primary" href="{% url 'auth:login' %}?next={{ request.path }}"
                   tabindex="-1"
                   aria-disabled="true">Комментировать</a>
                <a class="btn btn-outline-primary"
                   href="{% url 'auth:login' %}?next={{ request.path }}"><i
                        class="fa fa-heart" aria-hidden="true"></i>{{ post.like_quantity }}</a>
                {% endif %}
            </nav>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}